
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.ButtonGroup;

public class NewJFrame extends javax.swing.JFrame {
    
    String radioText="";
    Connection con1= null;
    PreparedStatement statement1= null;
    ResultSet set1= null;
    public NewJFrame() {
        initComponents();
         showTableData();
         groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Roll_No = new javax.swing.JTextField();
        First_Name = new javax.swing.JTextField();
        Last_Name = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");

        jLabel1.setText("Registration No.");

        jLabel2.setText("First_Name");

        jLabel3.setText("Last_Name");

        jLabel4.setText("Address");

        Roll_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Roll_NoActionPerformed(evt);
            }
        });

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 51)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Registration No.", "First Name", "Last Name", "Address", "Gender"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jRadioButton1.setText("Male");

        jRadioButton2.setText("Female");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Address)
                                    .addComponent(Last_Name)
                                    .addComponent(First_Name)
                                    .addComponent(Roll_No)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Roll_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try{
    
    if(jRadioButton1.isSelected()){
       radioText= jRadioButton1.getText();
    }
    if(jRadioButton2.isSelected()){
       radioText= jRadioButton2.getText();
    }
    
            String sql ="INSERT INTO indusjavanew2"
                    + "(Roll_No, First_Name, Last_Name, Address, Gender)"
                    + " VALUES (?,?,?,?,?)";
       con1= DriverManager.getConnection("jdbc:mysql://localhost/indusjavanew2","root","");
       statement1=con1.prepareStatement(sql);//assignment of value to PreparedStatement declared earlier to be used as SQl command in database
       statement1.setString(1,Roll_No.getText());//getting
       statement1.setString(2,First_Name.getText());//User
       statement1.setString(3,Last_Name.getText());//Input
       statement1.setString(4,Address.getText());//from Jframe form textfields
       statement1.setString(5,radioText);
       statement1.executeUpdate();//Method that executes update process
       showTableData();
       clear();
        JOptionPane.showMessageDialog(null,"Inserted Succesfully");
        }
        catch (SQLException |HeadlessException ex){
        JOptionPane.showMessageDialog(null,"Insertion Failed");    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Roll_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Roll_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Roll_NoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

     try{
            String sql ="DELETE FROM indusjavanew2 WHERE Roll_No=? ";
       con1= DriverManager.getConnection("jdbc:mysql://localhost/indusjavanew2","root","");
       statement1=con1.prepareStatement(sql);//assignment of value to PreparedStatement declared earlier to be used as SQl command in database
       statement1.setString(1,Roll_No.getText());//getting
       statement1.executeUpdate();//Method that executes update process
       JOptionPane.showMessageDialog(null,"Deleted Succesfully");
       showTableData();
       clear();
        }
        catch (SQLException |HeadlessException ex){
        JOptionPane.showMessageDialog(null,"Deletion Failed");    
        }   
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try{
          
    if(jRadioButton1.isSelected()){
       radioText= jRadioButton1.getText();
    }
    if(jRadioButton2.isSelected()){
       radioText= jRadioButton2.getText();
    }
          
            String sql ="UPDATE indusjavanew2 SET First_Name=?,Last_Name=?,Address=?,Gender=? WHERE Roll_No=?";
       con1= DriverManager.getConnection("jdbc:mysql://localhost/indusjavanew2","root","");
       statement1=con1.prepareStatement(sql);//assignment of value to PreparedStatement declared earlier to be used as SQl command in database
       statement1.setString(4,Roll_No.getText());//getting
       statement1.setString(1,First_Name.getText());//User
    
       statement1.setString(2,Last_Name.getText());//Input
       statement1.setString(3,Address.getText());//from Jframe form textfields
       statement1.setString(5,radioText);
       
 
       statement1.executeUpdate();//Method that executes update process
       JOptionPane.showMessageDialog(null,"Updated Succesfully");
       showTableData();
       clear();
        }
        catch (SQLException |HeadlessException ex){
        JOptionPane.showMessageDialog(null,"Update Failed");    
        }
    }//GEN-LAST:event_jButton3ActionPerformed
public void showTableData()
      {
        try{
           con1= DriverManager.getConnection("jdbc:mysql://localhost/indusjavanew2","root","");
           String sql="SELECT * FROM indusjavanew2";
           statement1= con1.prepareStatement(sql);
           set1=statement1.executeQuery();
           jTable1.setModel(DbUtils.resultSetToTableModel(set1));
           
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);    
        }
      }
public void clear()
{
 Roll_No.setText("");
 First_Name.setText("");
 Last_Name.setText("");
 Address.setText("");
}
private void groupButton(){
ButtonGroup bg1 = new ButtonGroup();
bg1.add(jRadioButton1);
bg1.add(jRadioButton2);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField First_Name;
    private javax.swing.JTextField Last_Name;
    private javax.swing.JTextField Roll_No;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
